vich_uploader:
    db_driver: orm
    mappings:
        pieces:
            uri_prefix: '/uploads/photos/piece'
            upload_destination: '%kernel.project_dir%/public/uploads/photos/piece'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true