vich_uploader:
    db_driver: orm
    mappings:
        categories:
            uri_prefix: '/uploads/images/categories'
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer